### ISSUE TITLE
Trigger new docker image build without push new commit?

### ISSUE THREAD

**Issue by comphilip** [onisuly/docker-aria2-with-webui#4]
Docker file download latest Aria2 package instead of using hard-code url. To update Aria2, just rebuild docker image without push git commit to trigger docker hub building.

Is there a way to trigger docker hub image build?
* Email @onisuly to let @onisuly manual trigger build in docker hub
* Share docker build trigger link to let others trigger building.

**Comment by onisuly** [comment]
I just created one new jenkins project on my server.

![Screenshot from 2019-10-09 20-37-36](https://user-images.githubusercontent.com/8399827/66482051-b0b30780-ead4-11e9-8c50-f57d24ca7bff.png)

```shell
publish_date=$(curl -sX GET "https://api.github.com/repos/mayswind/AriaNg/releases/latest" | awk '/published_at/{print $4;exit}' FS='[""]')
build_date=$(curl -sX GET "https://hub.docker.com/v2/repositories/onisuly/aria2-with-webui/" | grep -oP '(?<="last_updated": ")[^"]*' | cut -d '.' -f1 | awk '{print $1"Z"}')

if [ $publish_date \> $build_date ]
    then
        curl -X POST https://cloud.docker.com/api/build/v1/source/***/trigger/***/call/
    else
        echo "up to date"
fi
```

If the publish date is after build date, it will trigger the docker build action.

**Comment by somedevreally** [comment]
so aria2 be updated to v1.3.5?

**Comment by onisuly** [comment]
> so aria2 be updated to v1.3.5?

No, currently we only update aria ng, we still install aria2 from alpine's software repository which means it may not up to date. Maybe I'll update the dockerfile to compile aria2 so that keep it up to date later.

**Comment by somedevreally** [comment]
yes, updating dockerfile is great idea, thanks
