### ISSUE TITLE
AriaNg port variable

### ISSUE THREAD

**Issue by pwatk** [onisuly/docker-aria2-with-webui#5]
I cannot devote  port 80 to AriaNg on my NAS so I edited start.sh from within the container to use a different port.

Defining a variable for this port would make deployment easier .

**Comment by onisuly** [comment]
Hi pwatk,

Sorry, I don't have a NAS for testing, maybe you can leverage some port mapping tools provided by the NAS manufacturer to achieve this goal.

For a Linux based OS, you can simply to map tcp port 80 in the container to port 8080 on the Docker host by below command:
```shell
docker run -d --name aria2-webui \
-p 8080:80 -p 6800:6800 \
onisuly/aria2-with-webui
```

**Comment by pwatk** [comment]
Thanks. I fixed the issue.
